name: 'AppRun Dedicated Update Image'
description: 'Updates AppRun Dedicated application image by creating and activating a new version'
author: 'tokuhirom'

inputs:
  applicationID:
    description: 'Application ID (UUID)'
    required: true
  sakuraAccessToken:
    description: 'Sakura Access Token (UUID)'
    required: true
  sakuraAccessTokenSecret:
    description: 'Sakura Access Token Secret'
    required: true
  image:
    description: 'New container image name (e.g., nginx:latest)'
    required: true
  activate:
    description: 'Whether to activate the new version immediately (default: true)'
    required: false
    default: 'true'

outputs:
  version:
    description: 'The newly created version number'
  activeVersion:
    description: 'The activated version number (same as version if activate=true, otherwise the previously active version)'

runs:
  using: 'node20'
  main: 'dist/index.js'
